import { Button, VerticalBox, LineEdit, ListView } from "std-widgets.slint";
import {UIUser, UserSlot} from "./user-slot.slint";
import {FindUser} from "./find-user.slint";

export component AppWindow inherits Window {
    in property <bool> is_loading: false;
    in property <[UIUser]> users;

    callback user_selected(string);
    callback find_user(string);

    title: "GitHub powers!";

    width: 500px;
    height: 900px;

    VerticalLayout {
        min-width: 0cm;
        preferred-width: 0cm;
        spacing: 10px;
        padding: 10px;

        find_user := FindUser {
            height: 30px;

            is_loading: is_loading;

            find_user(name) => {
                debug("Finding user", name);

                root.find_user(name);
            }
        }

        Text {
            text: "Total users: " + users.length;
        }

        ListView {

            for user in users: UserSlot {
                user: user;

                user_selected(name) => {
                    debug("User selected", name);

                    root.user_selected(name);
                }
            }
        }
    }
}
