export struct UIUser {
  name: string,
  nickname: string,
  avatar_url: image,

  repo_count: string,
  follower_count: string,
  following_count: string,
  gist_count: string,
  collaborator_count: string,
}

export component UserSlot inherits VerticalLayout {
    in property <UIUser> user;

    callback user_selected(string);

    Rectangle {
        border-color: greenyellow;
        border-width: 2px;
        border-radius: 8px;

        background: mysurface.pressed || mysurface.has-hover ? #d7e9adac : transparent;

        HorizontalLayout {
            spacing: 10px;
            padding: 10px;

            Rectangle {
                width: 100px;
                height: 100px;

                border-radius: 50px;
                clip: true;

                Image {
                    source: user.avatar_url;

                    width: 100px;
                    height: 100px;
                }
            }

            VerticalLayout {
                Text {
                    text: user.name;
                    font-size: 24px;
                }

                Text {
                    text: user.nickname;
                    font-size: 18px;
                }

                HorizontalLayout {
                    spacing: 5px;
                    Image {
                        source: @image-url("images/repo.svg");
                        width: 24px;
                        height: 24px;
                    }

                    Text {
                        font-size: 18px;
                        vertical-alignment: TextVerticalAlignment.center;
                        text: user.repo_count;
                    }

                    Image {
                        source: @image-url("images/repo.svg");
                        width: 24px;
                        height: 24px;
                    }

                    Text {
                        font-size: 18px;
                        vertical-alignment: TextVerticalAlignment.center;
                        text: user.gist_count;
                    }

                    Image {
                        source: @image-url("images/repo.svg");
                        width: 24px;
                        height: 24px;
                    }

                    Text {
                        font-size: 18px;
                        vertical-alignment: TextVerticalAlignment.center;
                        text: user.follower_count;
                    }

                    Image {
                        source: @image-url("images/repo.svg");
                        width: 24px;
                        height: 24px;
                    }

                    Text {
                        font-size: 18px;
                        vertical-alignment: TextVerticalAlignment.center;
                        text: user.following_count;
                    }
                }
            }
        }

        mysurface := TouchArea {
            mouse-cursor: MouseCursor.pointer;

            clicked => {
                root.user_selected(user.nickname);
            }
        }
    }

    Rectangle {
        height: 8px;
    }
}
